package com.terrasystems.emedics.enums;


public enum MessageEnums {
    MSG_ERROR_SEND_MAIL,
    MSG_SEND_MAIL,
    MSG_EMAIL_EXIST,
    MSG_EMAIL_NOT_EXIST,
    MSG_USER_ACTIVED,
    MSG_SEND_LETTER,
    MSG_BAD,
    MSG_NOT_ACTIVATE,
    MSG_REQUEST_INCORRECT,
    MSG_EMPTY_EMAIL,
    MSG_REQUIRED_FIELDS_EXCEPTION,
    MSG_LOGINED,
    MSG_BAD_CREDENTIALS,
    MSG_PASS_CHANGED,
    MSG_VALID_EMAIL,
    MSG_VALID_KEY,
    MSG_TYPE_IS_NULL,
    MSG_PAT_REF,
    MSG_DOC_REF,
    MSG_STAFF_REF,
    MSG_REF_REMOVED,
    MSG_REF_ADDED,
    MSG_USER_NOT_FOUND,
    MSG_REF_CREATED,
    MSG_NOT_SUPPORTED,
    MSG_SEARCH_IS_NULL,
    MSG_BAD_REQUEST,
    MSG_REF_BY_ID
}
